database:
  driver: "mysql"

  dbname:
  username:
  password:
  host:
  port: "3306"
  logmode: true

redis:
  redishost:
  redisport:

server:
  port:
  secret:
  accessTokenExpireDuration: 
  refreshTokenExpireDuration: 
  limitCountPerRequest: 

params:
  masterPassword:
  sentrydsn:
  environment:
  debug: true
  release:
  stackTract: true
  appBaseUrl:

Notification:
  baseUrl:

email:
  emailUser:
  emailPassword:
  emailHost:
  emailPort: