version: '3.9'

services:
  database:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      command: echo ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  main-api:
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    build:
      dockerfile: docker/build/Dockerfile
      context: .
    env_file:
      - .env

    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      APP_ENV: ${APP_ENV}
      HTTP_PORT: ${HTTP_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    links:
      - database
      - redis

    ports:
      - "8080:8080"

volumes:
  dbdata: